#!/bin/bash

function yakuake--set-title {
    title="${1}"

    qdbus org.kde.yakuake /yakuake/tabs org.kde.yakuake.setTabTitle `qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.activeSessionId` "${title}"
}

function yakuake--set-title-and-open-screen {
    title="${1}"

    yakuake--set-title "${title}"
    screen -S "${title}"
}


function _project-ask-for-type-and-projects-path {
	_projectProjectsPath=~/dev/projects
	
	if [ "${1}" != '' ]; then
		type="${1}"
	else
        	ls -1 ${pathProjects}

	        echo -n 'Project type: '
	        read type
	fi
	
	pathProjects="${_projectProjectsPath}/${type}"
}

function project-ls {
    _project-ask-for-type-and-projects-path "${1}"

    projectsList="`ls ${pathProjects} -1`"

    echo "${projectsList}"| cat -n

    echo -n "Open project with number: "
    read projectIndex

    if [ "${projectIndex}" != '' ]; then
        name=$(echo "${projectsList}" | awk '{if(NR=='${projectIndex}'){print $0}}')
    fi

    if [ "${name}" ]; then
        project-cd "${type}" "${name}"
    fi
}

function project-cd {
    pathProjects=~/dev/projects

    name="${2}"
    type="${1}"

    pathProject="${pathProjects}/${type}/${name}"

    if [ ! -e "${pathProject}" ]; then
        echo "${pathProject} not exists"
    else
        cd "${pathProject}" && yakuake--set-title-and-open-screen "${name}"
    fi
}

function project-clone {
	_project-ask-for-type-and-projects-path "${2}"

	cd ~/dev/projects/"${type}" &&
 	 git clone "${1}"
}
