#!/bin/bash

alias ti="tsd install --save"
alias ts="tsd query"

function tsdInstall {
    tsd query "${1}" -sr -a install
}

function compileApp {
    find scripts/ -name '_*.ts' > /tmp/list &&
     find scripts/ -name '*.ts' -not -name '_*.ts' >> /tmp/list &&
     tsc --target es5 --out app.js `cat /tmp/list | tr "\n" ' '` &&
#     grep "script src=.bower_components" index.html | sed -e 's/.*script src=.\(.*\).><\/script.*/\1/' > /tmp/list-bower &&
#     uglifyjs `cat /tmp/list-bower | tr "\n" ' '` app.js -o app.min.js
     uglifyjs  app.js -o app.min.js
}
